# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GxGit < Formula
  desc "Git Productivity Toolkit: smart undo, stacking, branch management and more"
  homepage "https://github.com/mubbie/gx-cli"
  version "2.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mubbie/gx-cli/releases/download/v2.5.0/gx_2.5.0_darwin_amd64.tar.gz"
      sha256 "b0512761c75c0c093603a48c495f1169d5b35de9b039fc418e850396f562b113"

      define_method(:install) do
        bin.install "gx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mubbie/gx-cli/releases/download/v2.5.0/gx_2.5.0_darwin_arm64.tar.gz"
      sha256 "f54becf853a667335f5baa9a1cef9cf6ef31bfb7e29ef03ec46b7379dc749b46"

      define_method(:install) do
        bin.install "gx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mubbie/gx-cli/releases/download/v2.5.0/gx_2.5.0_linux_amd64.tar.gz"
      sha256 "45b10978fc27906f526dd55b63b1f3c6ebc8d79057d25ef0a7053670b98f1002"
      define_method(:install) do
        bin.install "gx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mubbie/gx-cli/releases/download/v2.5.0/gx_2.5.0_linux_arm64.tar.gz"
      sha256 "9af6df251f40388ccab5aec607a07c022611775682ff720b70d208dc09cf1d93"
      define_method(:install) do
        bin.install "gx"
      end
    end
  end

  test do
    assert_match "gx", shell_output("#{bin}/gx --version")
  end
end
