# typed: false
# frozen_string_literal: true

# Auto-generated by gx-git release pipeline. DO NOT EDIT.
class GxGit < Formula
  desc "Git Productivity Toolkit: smart undo, stacking, branch management and more"
  homepage "https://github.com/mubbie/gx-cli"
  version "1.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mubbie/gx-cli/releases/download/v1.5.5/gx_1.5.5_darwin_arm64.tar.gz"
      sha256 "654f1c734b45f8b83f3c67126c2b5ad2dd4b694e530493ac315d6a8abfdbdae7"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mubbie/gx-cli/releases/download/v1.5.5/gx_1.5.5_linux_amd64.tar.gz"
      sha256 "ef6da4ebffc3ffa65af08d5dbf52f896f552c3154a86aaa3b6727c88acd74c05"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mubbie/gx-cli/releases/download/v1.5.5/gx_1.5.5_linux_arm64.tar.gz"
      sha256 "5a41d4198c38c4bfc2e17889c1bcc7b66fab44438c7aa549f49515ae9819e38b"
    end
  end

  def install
    bin.install "gx"
  end

  test do
    assert_match "gx", shell_output("#{bin}/gx --version")
  end
end
