# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gx < Formula
  desc "Git Productivity Toolkit: smart undo, stacking, branch management and more"
  homepage "https://github.com/mubbie/gx-cli"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mubbie/gx-cli/releases/download/v2.0.0/gx_2.0.0_darwin_amd64.tar.gz"
      sha256 "ef842a470b6779a6aa27ef4891571b42c97201469f8844d5866ac69a09aa5b4c"

      define_method(:install) do
        bin.install "gx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mubbie/gx-cli/releases/download/v2.0.0/gx_2.0.0_darwin_arm64.tar.gz"
      sha256 "5f557e5bba03be6ff818b6eefce145f3f5a08f87cb30e016226f9ea1e57cedca"

      define_method(:install) do
        bin.install "gx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mubbie/gx-cli/releases/download/v2.0.0/gx_2.0.0_linux_amd64.tar.gz"
      sha256 "1ee5c111d7e3b7bfd80cfb1b75a829e1692fd3ca2e3c8b348b1d5f90f29d87cc"
      define_method(:install) do
        bin.install "gx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mubbie/gx-cli/releases/download/v2.0.0/gx_2.0.0_linux_arm64.tar.gz"
      sha256 "4f1e3968786f6a5d323fd3ed1c62ccf00aa2e545baf5d78a23803b44fc2f9460"
      define_method(:install) do
        bin.install "gx"
      end
    end
  end

  test do
    assert_match "gx", shell_output("#{bin}/gx --version")
  end
end
