# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacksmith < Formula
  desc "Ultralight Artisan Git Stacking Tool"
  homepage "https://github.com/mubbie/stacksmith"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_darwin_amd64.tar.gz"
      sha256 "a332830c2e8cb4c0fa5d125574d04a3cb20b71f74c29abad8b9bba11e57ae81c"

      def install
        bin.install "stacksmith"
        bash_completion.install "build/completions/stacksmith.bash"
        zsh_completion.install "build/completions/stacksmith.zsh"
        fish_completion.install "build/completions/stacksmith.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_darwin_arm64.tar.gz"
      sha256 "cc3651a38eabedd33bd0dfa6395e7b5bf08656317689774081aab0a464824d4b"

      def install
        bin.install "stacksmith"
        bash_completion.install "build/completions/stacksmith.bash"
        zsh_completion.install "build/completions/stacksmith.zsh"
        fish_completion.install "build/completions/stacksmith.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_linux_amd64.tar.gz"
        sha256 "da8bfb8cbeecda8daf1cfba4ae26af315ad9cb87879cfdf756a706ff23132f5c"

        def install
          bin.install "stacksmith"
          bash_completion.install "build/completions/stacksmith.bash"
          zsh_completion.install "build/completions/stacksmith.zsh"
          fish_completion.install "build/completions/stacksmith.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_linux_arm64.tar.gz"
        sha256 "97529230e9d3bc78b468046c5826eb67b48b3cce473cbb533d480ba08c361ebe"

        def install
          bin.install "stacksmith"
          bash_completion.install "build/completions/stacksmith.bash"
          zsh_completion.install "build/completions/stacksmith.zsh"
          fish_completion.install "build/completions/stacksmith.fish"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions:

        Bash:
          source $(brew --prefix)/etc/bash_completion
          source $(brew --prefix)/etc/bash_completion.d/stacksmith.bash

        Zsh:
          autoload -Uz compinit && compinit
          fpath+=~/.zsh/completion  # if applicable
          compdef _stacksmith stacksmith

        Fish:
          source (brew --prefix)/share/fish/vendor_completions.d/stacksmith.fish
    EOS
  end

  test do
    system "#{bin}/stacksmith", "--help"
  end
end
