# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacksmith < Formula
  desc "Ultralight Artisan Git Stacking Tool"
  homepage "https://github.com/mubbie/stacksmith"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_darwin_amd64.tar.gz"
      sha256 "5b6aa5d1780f0a30c529fccdcc283f616ce58b5b26f4ff3231ad9e9e894570e0"

      def install
        bin.install "stacksmith"
        bash_completion.install "completions/stacksmith.bash"
        zsh_completion.install "completions/stacksmith.zsh"
        fish_completion.install "completions/stacksmith.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_darwin_arm64.tar.gz"
      sha256 "b0dcccdaccf375f47820bc2e90dad0387207c596b3b10dc91f8077f548f7fad4"

      def install
        bin.install "stacksmith"
        bash_completion.install "completions/stacksmith.bash"
        zsh_completion.install "completions/stacksmith.zsh"
        fish_completion.install "completions/stacksmith.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_linux_amd64.tar.gz"
        sha256 "9287970a6d8dc1c1c7f37471c5dc7797fb376c35d7f739dd84d289e7148bcd2d"

        def install
          bin.install "stacksmith"
          bash_completion.install "completions/stacksmith.bash"
          zsh_completion.install "completions/stacksmith.zsh"
          fish_completion.install "completions/stacksmith.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_linux_arm64.tar.gz"
        sha256 "ca5a14934a7e1b691e4616544a2c49369bc16cd19ac8644a3777f278b8beb060"

        def install
          bin.install "stacksmith"
          bash_completion.install "completions/stacksmith.bash"
          zsh_completion.install "completions/stacksmith.zsh"
          fish_completion.install "completions/stacksmith.fish"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions:

        Bash:
          source $(brew --prefix)/etc/bash_completion
          source $(brew --prefix)/etc/bash_completion.d/stacksmith.bash

        Zsh:
          autoload -Uz compinit && compinit
          fpath+=~/.zsh/completion  # if applicable
          compdef _stacksmith stacksmith

        Fish:
          source (brew --prefix)/share/fish/vendor_completions.d/stacksmith.fish
    EOS
  end

  test do
    system "#{bin}/stacksmith", "--help"
  end
end
