# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacksmith < Formula
  desc "Ultralight Artisan Git Stacking Tool"
  homepage "https://github.com/mubbie/stacksmith"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_darwin_amd64.tar.gz"
      sha256 "16f6473921c3c2e9cc18b00a9baa465222cb2be1efad2adadeaebefd2cb9d4c0"

      def install
        bin.install "stacksmith"
        bash_completion.install "completions/stacksmith.bash"
        zsh_completion.install "completions/stacksmith.zsh"
        fish_completion.install "completions/stacksmith.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_darwin_arm64.tar.gz"
      sha256 "83109735c50225d98017255525277995c69972a5def60f2178177c99f852c208"

      def install
        bin.install "stacksmith"
        bash_completion.install "completions/stacksmith.bash"
        zsh_completion.install "completions/stacksmith.zsh"
        fish_completion.install "completions/stacksmith.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_linux_amd64.tar.gz"
        sha256 "5f98130480a7051c2b66947800d8d123e108d13e7a6b1204b506747a1776e0cd"

        def install
          bin.install "stacksmith"
          bash_completion.install "completions/stacksmith.bash"
          zsh_completion.install "completions/stacksmith.zsh"
          fish_completion.install "completions/stacksmith.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mubbie/stacksmith/releases/download/v1.0.0/stacksmith_1.0.0_linux_arm64.tar.gz"
        sha256 "14de3f7a63cc0bfdf4457910b4f69a85427635a8791ea1ebbd5bd6f0bafc084a"

        def install
          bin.install "stacksmith"
          bash_completion.install "completions/stacksmith.bash"
          zsh_completion.install "completions/stacksmith.zsh"
          fish_completion.install "completions/stacksmith.fish"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions:

        Bash:
          source $(brew --prefix)/etc/bash_completion
          source $(brew --prefix)/etc/bash_completion.d/stacksmith.bash

        Zsh:
          autoload -Uz compinit && compinit
          fpath+=~/.zsh/completion  # if applicable
          compdef _stacksmith stacksmith

        Fish:
          source (brew --prefix)/share/fish/vendor_completions.d/stacksmith.fish
    EOS
  end

  test do
    system "#{bin}/stacksmith", "--help"
  end
end
